#!/usr/bin/env ruby
# frozen_string_literal: true

require "glossaby"
require "commander"

module Glossaby
  # Implements CLI interface.
  class CLI
    include Commander::Methods

    def run
      program :name, "glossaby"
      program :version, Glossaby::VERSION
      program :description, "Making glossary easy"

      command :ner do |c|
        c.syntax = "#{program :name} #{c.name} [file]"
        c.description = "Create a list of Named Entity"
        c.option "--filter STRING", String, "Filter name"
        c.action do |args, options|
          Glossaby::NER.new(args: args, options: options).run
        end
      end

      run!
    end
  end
end

Glossaby::CLI.new.run
