---
name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        # see https://www.ruby-lang.org/en/downloads/ for stable versions
        ruby:
          - "3.4"
          - "3.3"
          - "3.2"

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install spacy
        run: |
          pip install spacy
          python -m spacy download en_core_web_sm

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run the default task
        run: bundle exec rake
